### ISSUE TITLE
Programming Firmware SPI flash

### ISSUE THREAD

**Issue by alex-dewar** [newaetech/sonata-rp2040#4]
Allow programming of the firmware SPI flash. Will probably need to autodetect firmware vs. bitstream vs. OS files

**Comment by alex-dewar** [comment]
Could potentially use UF2 file format: https://github.com/microsoft/uf2

Would make it very easy to tell what is/isn't firmware, gives the file size, includes a checksum, etc.

**Comment by marnovandermaas** [comment]
Yes, this looks pretty nice. You could even use [extension tags](https://github.com/microsoft/uf2?tab=readme-ov-file#extension-tags) for a SHA2 checksum and to have a custom identifier for different types of files.
